### ISSUE TITLE
ModuleNotFoundError: No module named 'RLE'

### ISSUE THREAD

**Issue by bergstar** [Photonsters/PhotonFileEditor-v2#4]
`
python3 PhotonFileEditor.py 
Traceback (most recent call last):
  File "PhotonFileEditor.py", line 39, in <module>
    import PhotonFile 
  File "/media/gc/6TB/SLA/Photonsters-FileEditor-v2/PhotonFile.py", line 34, in <module>
    import RLE
ModuleNotFoundError: No module named 'RLE'
`

Tried with 3.7. I really want to get this software running, since previous version is not able to generate valid .photon files.

**Comment by NardJ** [comment]
Will look into this! One question beforehand: are you running a 32 or 64
bit OS?

(I did test current version on 64 bit Windows 10 and 64 bit Linux Mint)

Op vr 25 okt. 2019 om 20:59 schreef Dmitry K Valberg <
notifications@github.com>

**Comment by NardJ** [comment]
Oh and did you use the development branch?

Op vr 25 okt. 2019 om 20:59 schreef Dmitry K Valberg <
notifications@github.com>

**Comment by bergstar** [comment]
@NardJ Yes, this is what I did:
Fresh Ubuntu 19.10 install (confirmed on a new Linode VPS)
```
sudo apt-get install python3-tk python3-pil.imagetk python3-pip python3-opencv
git clone https://github.com/Photonsters/Photonsters-FileEditor-v2.git
git checkout v0.1-development
python3 PhotonFileEditor.py
Traceback (most recent call last):
  File "PhotonFileEditor.py", line 39, in <module>
    import PhotonFile
  File "/root/Photonsters-FileEditor-v2/PhotonFile.py", line 34, in <module>
    import RLE
ModuleNotFoundError: No module named 'RLE'

```

**Comment by NardJ** [comment]
@bergstar. I was a bit further with my local development. So easier to update the entire branch. The main file is now called PhotonFileEdit2.py. (Beware this is still alpha.)

**Comment by bergstar** [comment]
@NardJ I did test with latest code on a new Linode box,
```
root@localhost:~/Photonsters-FileEditor-v2# python3 PhotonFileEditor2.py 
Traceback (most recent call last):
  File "PhotonFileEditor2.py", line 45, in <module>
    import PhotonFile 
  File "/root/Photonsters-FileEditor-v2/PhotonFile.py", line 34, in <module>
    import RLE
ModuleNotFoundError: No module named 'RLE
```
Same issue

**Comment by MaksymMikolajczyk** [comment]
Win 10 x64, same issue.

**Comment by ForceFedDSM** [comment]
I am using Win 10 x64 and having the issue as well.

**Comment by al37919** [comment]
To resolve this issue, rebuild RLE following the instructions in the file compileRLE.py

Actually files:

RLE.c
RLE.cpython-36m-x86_64-linux-gnu.so
RLE.html
rleEncode.cp36-win_amd64.pyd
rleEncode.cp37-win_amd64.pyd
rleEncode.cpython-36m-x86_64-linux-gnu.so

should be removed from the distribution, because these are generated files
